// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package CatanSimulatorDomainModel.catanUML;

/************************************************************/
/**
 * 
 */
public interface ActionVisitor {
	/**
	 * 
	 * @return 
	 * @param action 
	 */
	public float visit(BuildRoadAction action);

	/**
	 * 
	 * @return 
	 * @param action 
	 */
	public float visit(BuildSettlementAction action);

	/**
	 * 
	 * @return 
	 * @param action 
	 */
	public float visit(BuildCityAction action);

	/**
	 * 
	 * @return 
	 * @param action 
	 */
	public float visit(PassAction action);

	/**
	 * 
	 * @return 
	 * @param action 
	 */
	public float visit(RollAction action);
}
