// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package CatanSimulatorDomainModel.catanUML;

/************************************************************/
/**
 * 
 */
public class AIPlayer extends RuleBasedAIPlayer {
	/**
	 * 
	 */
	public ScoredAction scoredaction;

	/**
	 * 
	 * @return 
	 */
	private PlayerAction checkBankTrade() {
	}

	/**
	 * 
	 * @param game 
	 * @param mustBuild 
	 * @return 
	 */
	protected PlayerAction decideMove(GameMaster game, boolean mustBuild) {
	}

	/**
	 * 
	 * @param game 
	 */
	public void takeTurn(GameMaster game) {
	}

	/**
	 * 
	 * @param game 
	 * @return 
	 */
	protected PlayerAction resolveConstraint(GameMaster game) {
	}

	/**
	 * 
	 * @param game 
	 * @return 
	 */
	protected PlayerAction pickBestValueMove(GameMaster game) {
	}
}
