// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package CatanSimulatorDomainModel.catanUML;

/************************************************************/
/**
 * 
 */
public class Board {
	/**
	 * 
	 */
	private Tile[] tiles;
	/**
	 * 
	 */
	private Vertex[] vertices;
	/**
	 * 
	 */
	private Road[] roads;

	/**
	 * 
	 */
	public void initializeDefaultMap() {
	}

	/**
	 * 
	 * @param id 
	 * @return 
	 */
	public Tile getTile(int id) {
	}

	/**
	 * 
	 * @param id 
	 * @return 
	 */
	public Vertex getVertex(int id) {
	}

	/**
	 * 
	 * @param road 
	 */
	public void placeRoad(Road road) {
	}

	/**
	 * 
	 * @param building 
	 */
	public void placeBuilding(Buildings building) {
	}
}
