// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package CatanSimulatorDomainModel.catanUML;

/************************************************************/
/**
 * 
 */
public class Board {
	/**
	 * 
	 */
	private Tile[] tiles;
	/**
	 * 
	 */
	private Vertex[] vertices;
	/**
	 * 
	 */
	private Road[] roads;
	/**
	 * 
	 */
	public Tile[] tile;
	/**
	 * 
	 */
	public Vertex[] vertex;
	/**
	 * 
	 */
	public Road[] road;

	/**
	 * 
	 */
	public void initializeDefaultMap() {
	}

	/**
	 * 
	 * @param id 
	 * @return 
	 */
	public Tile getTile(int id) {
	}

	/**
	 * 
	 * @param id 
	 * @return 
	 */
	public Vertex getVertex(int id) {
	}

	/**
	 * 
	 * @param road 
	 */
	public void placeRoad(Road road) {
	}

	/**
	 * 
	 * @param building 
	 */
	public void placeBuilding(Buildings building) {
	}

	/**
	 * 
	 */
	private void setupVertexAdjacencies() {
	}

	/**
	 * 
	 */
	private void setupTileVertexAdjacencie() {
	}

	/**
	 * 
	 * @param v1Id 
	 * @param v2Id 
	 */
	private void addVertexConnection(int v1Id, int v2Id) {
	}

	/**
	 * 
	 * @param tileId 
	 * @param vertexIds 
	 */
	private void addTileVertices(int tileId, int[] vertexIds) {
	}

	/**
	 * 
	 * @return 
	 */
	public Tile[] getTiles() {
	}

	/**
	 * 
	 * @return 
	 */
	public Vertex[] getVertices() {
	}

	/**
	 * 
	 * @return 
	 */
	public Road[] getRoads() {
	}

	/**
	 * 
	 */
	public void Board() {
	}
}
