// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package CatanSimulatorDomainModel.catanUML;

/************************************************************/
/**
 * 
 */
public abstract class Buildings {
	/**
	 * 
	 */
	protected Player owner;
	/**
	 * 
	 */
	protected Vertex location;

	/**
	 * 
	 * @return 
	 */
	public int getVictoryPoints() {
	}

	/**
	 * 
	 * @param vertex 
	 */
	public void placeOn(Vertex vertex) {
	}
}
