// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package CatanSimulatorDomainModel.catanUML;

/************************************************************/
/**
 * 
 */
public abstract class Buildings {
	/**
	 * 
	 */
	protected Player owner;
	/**
	 * 
	 */
	protected Vertex location;

	/**
	 * 
	 * @return 
	 */
	public abstract int getVictoryPoints();

	/**
	 * 
	 * @param vertex 
	 */
	public void placeOn(Vertex vertex) {
	}

	/**
	 * 
	 * @return 
	 */
	public Player getOwner() {
	}

	/**
	 * 
	 * @return 
	 */
	public Vertex getLocation() {
	}

	/**
	 * 
	 * @param owner 
	 */
	public void Buildings(Player owner) {
	}
}
