// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package CatanSimulatorDomainModel.catanUML;

/************************************************************/
/**
 * 
 */
public class BuildSettlementAction extends PlayerAction {
	/**
	 * 
	 */
	private Vertex location;
	/**
	 * 
	 */
	private Settlement placedSettlement;

	/**
	 * 
	 * @param game 
	 */
	public void execute(GameMaster game) {
	}

	/**
	 * 
	 * @return 
	 */
	public String describe() {
	}

	/**
	 * 
	 * @return 
	 */
	public Vertex getLocation() {
	}

	/**
	 * 
	 * @param player 
	 * @param location 
	 */
	public void BuildSettlementAction(Player player, Vertex location) {
	}

	/**
	 * 
	 * @param game 
	 */
	public void undo(GameMaster game) {
	}
}
