// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package CatanSimulatorDomainModel.catanUML;

/************************************************************/
/**
 * 
 */
public class BuildCityAction extends PlayerAction {
	/**
	 * 
	 */
	private Vertex location;
	/**
	 * 
	 */
	private Settlement replacedSettlement;

	/**
	 * 
	 * @param game 
	 */
	public void execute(GameMaster game) {
	}

	/**
	 * 
	 * @return 
	 */
	public String describe() {
	}

	/**
	 * 
	 * @return 
	 */
	public Vertex getLocation() {
	}

	/**
	 * 
	 * @param player 
	 * @param location 
	 */
	public void BuildCityAction(Player player, Vertex location) {
	}

	/**
	 * 
	 * @param game 
	 */
	public void undo(GameMaster game) {
	}

	/**
	 * 
	 * @return 
	 * @param visitor 
	 */
	public float accept(ActionVisitor visitor) {
	}
}
