// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package CatanSimulatorDomainModel.catanUML;

/************************************************************/
/**
 * 
 */
public class BuildRoadAction extends PlayerAction {
	/**
	 * 
	 */
	private Vertex start;
	/**
	 * 
	 */
	private Vertex end;
	/**
	 * 
	 */
	private Road placedRoad;

	/**
	 * 
	 * @param game 
	 */
	public void execute(GameMaster game) {
	}

	/**
	 * 
	 * @return 
	 */
	public String describe() {
	}

	/**
	 * 
	 * @return 
	 */
	public Vertex getStart() {
	}

	/**
	 * 
	 * @return 
	 */
	public Vertex getEnd() {
	}

	/**
	 * 
	 * @param player 
	 * @param start 
	 * @param end 
	 */
	public void BuildRoadAction(Player player, Vertex start, Vertex end) {
	}

	/**
	 * 
	 * @param game 
	 */
	public void undo(GameMaster game) {
	}

	/**
	 * 
	 * @return 
	 * @param visitor 
	 */
	public float accept(ActionVisitor visitor) {
	}
}
