// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package CatanSimulatorDomainModel.catanUML;

/************************************************************/
/**
 * 
 */
public class Class52 {
	/**
	 * 
	 * @return 
	 */
	public boolean canUndo() {
	}

	/**
	 * 
	 * @return 
	 */
	public boolean canRedo() {
	}
}
