// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package CatanSimulatorDomainModel.catanUML;

/************************************************************/
/**
 * 
 */
public class CommandManager {
	/**
				 * 
				 */
				private undef undoStack:Deque<PlayerAction>;
	/**
				 * 
				 */
				private undef redoStack:Deque<PlayerAction>;
	/**
	 * 
	 */
	public PlayerAction playeraction;

	/**
	 * 
	 * @param action 
	 * @param game 
	 */
	public void executeCommand(PlayerAction action, GameMaster game) {
	}

	/**
	 * 
	 * @param game 
	 * @return 
	 */
	public boolean undo(GameMaster game) {
	}

	/**
	 * 
	 * @param game 
	 * @return 
	 */
	public boolean redo(GameMaster game) {
	}

	/**
	 * 
	 * @return 
	 */
	public boolean canUndo() {
	}

	/**
	 * 
	 * @return 
	 */
	public boolean canRedo() {
	}

	/**
	 * 
	 */
	public void clearHistory() {
	}
}
