// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package CatanSimulatorDomainModel.catanUML;

/************************************************************/
/**
 * 
 */
class Cost {
	/**
	 * 
	 */
	private int wood;
	/**
	 * 
	 */
	private int brick;
	/**
	 * 
	 */
	private int wheat;
	/**
	 * 
	 */
	private int sheep;
	/**
	 * 
	 */
	private int ore;

	/**
	 * 
	 * @param hand 
	 * @param  
	 */
	public void isAffordableBy(ResourceHand hand, boolean ) {
	}

	/**
	 * 
	 * @return 
	 */
	public int getWood() {
	}

	/**
	 * 
	 * @return 
	 */
	public int getBrick() {
	}

	/**
	 * 
	 * @return 
	 */
	public int getWheat() {
	}

	/**
	 * 
	 * @return 
	 */
	public int getOre() {
	}

	/**
	 * 
	 * @return 
	 */
	public int getSheep() {
	}

	/**
	 * 
	 * @param wood 
	 * @param brick 
	 * @param ore 
	 * @param sheep 
	 * @param wheat 
	 */
	public void Cost(int wood, int brick, int ore, int sheep, int wheat) {
	}

	/**
	 * 
	 * @return 
	 */
	public static Cost roadCost() {
	}

	/**
	 * 
	 * @return 
	 */
	public static Cost settlementCost() {
	}

	/**
	 * 
	 * @return 
	 */
	public static Cost cityCost() {
	}
}
