// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package CatanSimulatorDomainModel.catanUML;

/************************************************************/
/**
 * 
 */
public class Cost {
	/**
	 * 
	 */
	private int wood;
	/**
	 * 
	 */
	private int brick;
	/**
	 * 
	 */
	private int wheat;
	/**
	 * 
	 */
	private int sheep;
	/**
				 * 
				 */
				private int ore;

	/**
	 * 
	 * @param hand 
	 * @param  
	 */
	public void isAffordableBy(ResourceHand hand, boolean ) {
	}
}
