// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package CatanSimulatorDomainModel.catanUML;

/************************************************************/
/**
 * 
 */
public class Demonstrator {
	/**
	 * 
	 */
	public class ConfigReader {
		/**
		 * 
		 */
		public int maxTurns;

		/**
		 * 
		 * @param configFilePath 
		 */
		public void ConfigReader(String configFilePath) {
		}

		/**
		 * 
		 * @param configFilePath 
		 */
		private void readConfig(String configFilePath) {
		}

		/**
		 * 
		 * @return 
		 */
		public int getMaxTurns() {
		}

		/**
		 * 
		 * @return 
		 */
		public int getMaxRounds() {
		}
	};

	/**
	 * 
	 * @param args 
	 */
	public void main(String[] args) {
	}

	/**
	 * 
	 * @param maxRounds 
	 */
	public void runCustomDemo(int maxRounds) {
	}

	/**
	 * 
	 * @param P 
	 * @param candidate 
	 * @param game 
	 * @return 
	 */
	private boolean hasEssentialTrio(Player P, Vertex candidate, GameMaster game) {
	}

	/**
	 * 
	 * @param v 
	 * @param game 
	 * @return 
	 */
	public ResourceType[] getProducedResources(Vertex v, GameMaster game) {
	}
}
