// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package CatanSimulatorDomainModel.catanUML;

/************************************************************/
/**
 * 
 */
public class Dice {
	/**
	 * 
	 */
	private int die1;
	/**
	 * 
	 */
	private int die2;
	/**
	 * 
	 */
	private int random;

	/**
	 * 
	 * @return 
	 */
	public int roll() {
	}

	/**
	 * 
	 * @return 
	 */
	public int getLastRoll() {
	}

	/**
	 * 
	 */
	public void Dice() {
	}

	/**
	 * 
	 * @return 
	 */
	public int getDie1() {
	}

	/**
	 * 
	 * @return 
	 */
	public int getDie2() {
	}
}
