// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package CatanSimulatorDomainModel.catanUML;

/************************************************************/
/**
 * 
 */
public class GameMaster {
	/**
	 * 
	 */
	private Player[] players;
	/**
	 * 
	 */
	private int currentRound;
	/**
	 * 
	 */
	private Board board;
	/**
	 * 
	 */
	private Dice dice;
	/**
	 * 
	 */
	private int maxRounds;
	/**
	 * 
	 */
	public RuleValidator rulevalidator;

	/**
	 * 
	 */
	public void startSimulation() {
	}

	/**
	 * 
	 */
	public void runRound() {
	}

	/**
	 * 
	 * @param player  
	 */
	public void runTurn(Player player) {
	}

	/**
	 * 
	 * @return 
	 */
	public Player checkVictory() {
	}

	/**
	 * 
	 */
	public void printRoundSummary() {
	}
}
