// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package CatanSimulatorDomainModel.catanUML;

/************************************************************/
/**
 * 
 */
public class GameMaster {
	/**
	 * 
	 */
	private Player[] players;
	/**
	 * 
	 */
	private int currentRound;
	/**
	 * 
	 */
	private Board board;
	/**
	 * 
	 */
	private Dice dice;
	/**
	 * 
	 */
	private int maxRounds;
	/**
	 * 
	 */
	private static int MAX_VICTORY_POINTS;
	/**
	 * 
	 */
	public Player[] player;
	/**
	 * 
	 */
	public Board board;
	/**
	 * 
	 */
	public Dice dice;
	/**
	 * 
	 */
	public RuleValidator rulevalidator;

	/**
	 * 
	 */
	public void startSimulation() {
	}

	/**
	 * 
	 */
	public void runRound() {
	}

	/**
	 * 
	 * @param player  
	 */
	public void runTurn(Player player) {
	}

	/**
	 * 
	 * @return 
	 */
	public Player checkVictory() {
	}

	/**
	 * 
	 */
	public void printRoundSummary() {
	}

	/**
	 * 
	 * @param maxRounds 
	 */
	public void GameMaster(int maxRounds) {
	}

	/**
	 * 
	 */
	private void printFinalStandings() {
	}

	/**
	 * 
	 * @param player 
	 * @param action 
	 */
	public void logAction(Player player, String action) {
	}

	/**
	 * 
	 * @return 
	 */
	public Board getBoard() {
	}

	/**
	 * 
	 * @return 
	 */
	public Player[] getPlayers() {
	}

	/**
	 * 
	 * @param roll 
	 */
	private void produceResources(int roll) {
	}

	/**
	 * 
	 * @return 
	 */
	public Dice getDice() {
	}

	/**
	 * 
	 * @return 
	 */
	public RuleValidator getRuleValidator() {
	}

	/**
	 * 
	 * @return 
	 */
	public int getCurrentRound() {
	}

	/**
	 * 
	 * @return 
	 */
	public int getMaxRounds() {
	}
}
