// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package CatanSimulatorDomainModel.catanUML;

/************************************************************/
/**
 * 
 */
public class HumanPlayer extends Player {
	/**
	 * 
	 */
	private boolean hasRolled;

	/**
	 * 
	 * @return 
	 */
	private static final String REGEX_ROLL() {
	}

	/**
	 * 
	 * @return 
	 */
	private static final String REGEX_GO() {
	}

	/**
	 * 
	 * @return 
	 */
	private static final String REGEX_LIST() {
	}

	/**
	 * 
	 * @return 
	 */
	private static final String REGEX_BUILD_SETTLEMENT() {
	}

	/**
	 * 
	 * @return 
	 */
	private static final String REGEX_BUILD_CITY() {
	}

	/**
	 * 
	 * @return 
	 */
	private static final String REGEX_BUILD_ROAD() {
	}

	/**
	 * 
	 * @param id 
	 */
	public void HumanPlayer(int id) {
	}

	/**
	 * 
	 */
	public void discardHalf() {
	}

	/**
	 * 
	 * @param game 
	 * @param mustBuild 
	 * @return 
	 */
	protected PlayerAction decideMove(GameMaster game, boolean mustBuild) {
	}

	/**
	 * 
	 * @param game 
	 */
	public void takeTurn(GameMaster game) {
	}
}
