// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package CatanSimulatorDomainModel.catanUML;

/************************************************************/
/**
 * 
 */
public class Player {
	/**
	 * 
	 */
	private int id;
	/**
	 * 
	 */
	private ResourceHand hand;
	/**
	 * 
	 */
	private int victoryPoints;
	/**
	 * 
	 */
	private Road[] roadsBuilt;
	/**
	 * 
	 */
	private Buildings[] buildingsBuilt;
	/**
	 * 
	 */
	private int random;
	/**
	 * 
	 */
	public ResourceHand resourcehand;
	/**
	 * 
	 */
	public Buildings[] buildings;

	/**
	 * 
	 * @param game 
	 */
	public void takeTurn(GameMaster game) {
	}

	/**
	 * 
	 * @param resource 
	 * @param amount 
	 */
	public void collectResource(ResourceType resource, int amount) {
	}

	/**
	 * 
	 * @param cost 
	 * @return 
	 */
	public boolean canAfford(Cost cost) {
	}

	/**
	 * 
	 * @param cost 
	 */
	public void spendResources(Cost cost) {
	}

	/**
	 * 
	 * @param amount 
	 */
	public void addVictoryPoints(int amount) {
	}

	/**
	 * 
	 * @return 
	 */
	public int getVictoryPoints() {
	}

	/**
	 * 
	 * @param id 
	 */
	public void Player(int id) {
	}

	/**
	 * 
	 * @param game 
	 * @param mustBuild 
	 * @return 
	 */
	private PlayerAction decideMove(GameMaster game, boolean mustBuild) {
	}

	/**
	 * 
	 * @param road 
	 */
	public void addRoad(Road road) {
	}

	/**
	 * 
	 * @param building 
	 */
	public void addBuilding(Buildings building) {
	}

	/**
	 * 
	 * @return 
	 */
	public int getId() {
	}

	/**
	 * 
	 * @return 
	 */
	public ResourceHand getHand() {
	}

	/**
	 * 
	 * @return 
	 */
	public Road[] getRoadsBuilt() {
	}

	/**
	 * 
	 * @return 
	 */
	public Buildings[] getBuildingsBuilt() {
	}

	/**
	 * 
	 * @return 
	 */
	public String toString() {
	}
}
