// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package CatanSimulatorDomainModel.catanUML;

/************************************************************/
/**
 * 
 */
public abstract class PlayerAction {
	/**
	 * 
	 */
	protected Player player;
	/**
	 * 
	 */
	public Player player;

	/**
	 * 
	 * @param game 
	 */
	public void execute(GameMaster game) {
	}

	/**
	 * 
	 * @return 
	 */
	public String describe() {
	}

	/**
	 * 
	 * @return 
	 */
	public Player getPlayer() {
	}

	/**
	 * 
	 * @param player 
	 */
	public void PlayerAction(Player player) {
	}

	/**
	 * 
	 * @param game 
	 */
	public void undo(GameMaster game) {
	}

	/**
	 * 
	 * @return 
	 * @param visitor 
	 */
	public float accept(ActionVisitor visitor) {
	}
}
