// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package CatanSimulatorDomainModel.catanUML;

/************************************************************/
/**
 * 
 */
public class PlayerAction {
	/**
	 * 
	 */
	protected Player player;

	/**
	 * 
	 * @param game 
	 */
	public void execute(GameMaster game) {
	}

	/**
	 * 
	 * @return 
	 */
	public String describe() {
	}
}
