// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package CatanSimulatorDomainModel.catanUML;

/************************************************************/
/**
 * 
 */
public class Player {
	/**
	 * 
	 */
	private int id;
	/**
	 * 
	 */
	private ResourceHand hand;
	/**
	 * 
	 */
	private int victoryPoints;
	/**
	 * 
	 */
	private Road[] roadsBuilt;
	/**
	 * 
	 */
	private Buildings[] buildingsBuilt;

	/**
	 * 
	 * @param game 
	 */
	public void takeTurn(GameMaster game) {
	}

	/**
	 * 
	 * @param resource 
	 * @param amount 
	 */
	public void collectResource(ResourceType resource, int amount) {
	}

	/**
	 * 
	 * @param cost 
	 * @return 
	 */
	public boolean canAfford(Cost cost) {
	}

	/**
	 * 
	 * @param cost 
	 */
	public void spendResources(Cost cost) {
	}

	/**
	 * 
	 * @param amount 
	 */
	public void addVictoryPoints(int amount) {
	}

	/**
	 * 
	 * @return 
	 */
	public int getVictoryPoints() {
	}
}
