// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package CatanSimulatorDomainModel.catanUML;

/************************************************************/
/**
 * 
 */
public class ResourceHand {
	/**
	 * 
	 */
	private int wood;
	/**
	 * 
	 */
	private int brick;
	/**
	 * 
	 */
	private int wheat;
	/**
	 * 
	 */
	private int sheep;
	/**
	 * 
	 */
	private int ore;

	/**
	 * 
	 * @return 
	 */
	public int totalCards() {
	}

	/**
	 * 
	 * @param resource 
	 * @param amount 
	 */
	public void add(ResourceType resource, int amount) {
	}

	/**
	 * 
	 * @param resource 
	 * @param amount 
	 */
	public void remove(ResourceType resource, int amount) {
	}

	/**
	 * 
	 * @param cost 
	 * @param  
	 */
	public void hasEnough(Cost cost, boolean ) {
	}
}
