// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package CatanSimulatorDomainModel.catanUML;

/************************************************************/
/**
 * 
 */
public class Road {
	/**
	 * 
	 */
	private Vertex start;
	/**
	 * 
	 */
	private Vertex end;
	/**
	 * 
	 */
	private Player owner;

	/**
	 * 
	 * @param player 
	 * @return 
	 */
	public boolean isConnectedTo(Player player) {
	}

	/**
	 * 
	 * @param owner 
	 * @param start 
	 * @param end 
	 */
	public void Road(Player owner, Vertex start, Vertex end) {
	}

	/**
	 * 
	 * @param v1 
	 * @param v2 
	 * @return 
	 */
	public boolean connects(Vertex v1, Vertex v2) {
	}

	/**
	 * 
	 * @return 
	 */
	public Player getOwner() {
	}

	/**
	 * 
	 * @return 
	 */
	public Vertex getStart() {
	}

	/**
	 * 
	 * @return 
	 */
	public Vertex getEnd() {
	}

	/**
	 * 
	 * @return 
	 */
	public String toString() {
	}
}
