// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package CatanSimulatorDomainModel.catanUML;

/************************************************************/
/**
 * 
 */
public class Road {
	/**
	 * 
	 */
	private Vertex start;
	/**
	 * 
	 */
	private Vertex end;
	/**
	 * 
	 */
	private Player owner;

	/**
	 * 
	 * @param player 
	 * @return 
	 */
	public boolean isConnectedTo(Player player) {
	}
}
