// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package CatanSimulatorDomainModel.catanUML;

/************************************************************/
/**
 * 
 */
public class Robber {
	/**
	 * 
	 */
	private Tile currentTile;
	/**
	 * 
	 */
	public Tile tile;

	/**
	 * 
	 * @param initialTile 
	 */
	public void Robber(Tile initialTile) {
	}

	/**
	 * 
	 * @param newTile 
	 */
	public void moveTo(Tile newTile) {
	}

	/**
	 * 
	 * @return 
	 */
	public Tile getCurrentTile() {
	}

	/**
	 * 
	 * @param tile 
	 * @return 
	 */
	public boolean isBlocking(Tile tile) {
	}
}
