// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package CatanSimulatorDomainModel.catanUML;

/************************************************************/
/**
 * 
 */
public class RollAction extends PlayerAction {
	/**
				 * 
				 */
				private undef resourcesBefore:Map<Player,int[]>;
	/**
	 * 
	 */
	private Tile robberTileBefore;
	/**
	 * 
	 */
	private boolean snapshotTaken;

	/**
	 * 
	 * @param player 
	 */
	public void RollAction(Player player) {
	}

	/**
	 * 
	 * @param game 
	 */
	public void execute(GameMaster game) {
	}

	/**
	 * 
	 * @param game 
	 */
	public void undo(GameMaster game) {
	}

	/**
	 * 
	 * @return 
	 */
	public String describe() {
	}
}
