// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package CatanSimulatorDomainModel.catanUML;

/************************************************************/
/**
 * 
 */
public class RuleValidator {
	/**
	 * 
	 * @param player 
	 * @param start 
	 * @param end 
	 * @return 
	 */
	public boolean canBuildRoad(Player player, Vertex start, Vertex end) {
	}

	/**
	 * 
	 * @param player 
	 * @param location 
	 * @return 
	 */
	public boolean canBuildSettlement(Player player, Vertex location) {
	}

	/**
	 * 
	 * @param player 
	 * @param location 
	 * @return 
	 */
	public boolean canBuildCity(Player player, Vertex location) {
	}

	/**
	 * 
	 * @param location 
	 * @return 
	 */
	public boolean respectsDistanceRule(Vertex location) {
	}
}
