// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package CatanSimulatorDomainModel.catanUML;

/************************************************************/
/**
 * 
 */
public class RuleBasedAIPlayer extends Player {
	/**
	 * 
	 * @param id 
	 */
	protected void RuleBasedAIPlayer(int id) {
	}

	/**
	 * 
	 * @param game 
	 */
	public void takeTurn(GameMaster game) {
	}

	/**
	 * 
	 * @param game 
	 * @return 
	 */
	protected PlayerAction resolveConstraint(GameMaster game) {
	}

	/**
	 * 
	 * @param game 
	 * @return 
	 */
	protected PlayerAction pickBestValueMove(GameMaster game) {
	}

	/**
	 * 
	 * @param game 
	 * @return 
	 * @param mustBuild 
	 */
	protected PlayerAction decideMove(GameMaster game, boolean mustBuild) {
	}
}
