// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package CatanSimulatorDomainModel.catanUML;

/************************************************************/
/**
 * 
 */
public class ScoredAction {
	/**
	 * 
	 */
	private PlayerAction action;
	/**
	 * 
	 */
	private float value;
}
