// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package CatanSimulatorDomainModel.catanUML;

/************************************************************/
/**
 * 
 */
public class Settlement extends Buildings {
	/**
	 * 
	 * @return 
	 */
	public int getVictoryPoints() {
	}

	/**
	 * 
	 * @return 
	 */
	public String toString() {
	}

	/**
	 * 
	 * @param player 
	 */
	public void Settlement(Player player) {
	}
}
