// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package CatanSimulatorDomainModel.catanUML;

/************************************************************/
/**
 * 
 */
public class Tile {
	/**
	 * 
	 */
	private int id;
	/**
	 * 
	 */
	private ResourceType resourceType;
	/**
	 * 
	 */
	private int numberToken;
	/**
	 * 
	 */
	private Vertex[] adjacentVertices;

	/**
	 * 
	 * @return 
	 * @param roll 
	 */
	public void producesOnRoll(int roll) {
	}

	/**
	 * 
	 * @return 
	 */
	public ResourceType getResourceType() {
	}
}
