// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package CatanSimulatorDomainModel.catanUML;

/************************************************************/
/**
 * 
 */
public class Tile {
	/**
	 * 
	 */
	private int id;
	/**
	 * 
	 */
	private ResourceType resourceType;
	/**
	 * 
	 */
	private int numberToken;
	/**
	 * 
	 */
	private Vertex[] adjacentVertices;

	/**
	 * 
	 * @return 
	 * @param roll 
	 */
	public boolean producesOnRoll(int roll) {
	}

	/**
	 * 
	 * @return 
	 */
	public ResourceType getResourceType() {
	}

	/**
	 * 
	 * @param id 
	 * @param resourceType 
	 * @param numberToken 
	 */
	public void Tile(int id, ResourceType resourceType, int numberToken) {
	}

	/**
	 * 
	 * @param vertex 
	 */
	public void addAdjacentVertex(Vertex vertex) {
	}

	/**
	 * 
	 * @return 
	 */
	public int getId() {
	}

	/**
	 * 
	 * @return 
	 */
	public int getNumberToken() {
	}

	/**
	 * 
	 * @return 
	 */
	public Vertex[] getAdjacentVertices() {
	}

	/**
	 * 
	 * @return 
	 */
	public String toString() {
	}
}
