// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package CatanSimulatorDomainModel.catanUML;

/************************************************************/
/**
 * 
 */
public class ValueEvaluator extends ActionVisitor {
	/**
	 * 
	 */
	private ResourceHand hand;

	/**
	 * 
	 * @param hand 
	 */
	public void ValueEvaluator(ResourceHand hand) {
	}

	/**
	 * 
	 * @return 
	 * @param action 
	 */
	public float visit(BuildRoadAction action) {
	}

	/**
	 * 
	 * @return 
	 * @param action 
	 */
	public float visit(BuildSettlementAction action) {
	}

	/**
	 * 
	 * @return 
	 * @param action 
	 */
	public float visit(BuildCityAction action) {
	}

	/**
	 * 
	 * @return 
	 * @param action 
	 */
	public float visit(PassAction action) {
	}

	/**
	 * 
	 * @return 
	 * @param action 
	 */
	public float visit(RollAction action) {
	}
}
