// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package CatanSimulatorDomainModel.catanUML;

/************************************************************/
/**
 * 
 */
public class Vertex {
	/**
	 * 
	 */
	private int id;
	/**
	 * 
	 */
	private Buildings building;
	/**
	 * 
	 */
	private Vertex[] adjacentVertices;
	/**
	 * 
	 */
	public Buildings buildings;

	/**
	 * 
	 * @return 
	 */
	public boolean isOccupied() {
	}

	/**
	 * 
	 * @param player 
	 * @return 
	 */
	public boolean canBuild(Player player) {
	}

	/**
	 * 
	 * @param building 
	 */
	public void placeBuilding(Buildings building) {
	}

	/**
	 * 
	 * @param id 
	 */
	public void Vertex(int id) {
	}

	/**
	 * 
	 * @param vertex 
	 */
	public void addAdjacentVertex(Vertex vertex) {
	}

	/**
	 * 
	 * @return 
	 */
	public int getId() {
	}

	/**
	 * 
	 * @return 
	 */
	public Player getOwner() {
	}

	/**
	 * 
	 * @return 
	 */
	public Buildings getBuilding() {
	}

	/**
	 * 
	 * @return 
	 */
	public Vertex[] getAdjacentVertices() {
	}

	/**
	 * 
	 * @param building 
	 */
	public void setBuilding(Buildings building) {
	}
}
