// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package CatanSimulatorDomainModel.catanUML;

/************************************************************/
/**
 * 
 */
public class Vertex {
	/**
	 * 
	 */
	private int id;
	/**
	 * 
	 */
	private Player owner;
	/**
	 * 
	 */
	private Buildings building;
	/**
	 * 
	 */
	private Vertex[] adjacentVertices;

	/**
	 * 
	 * @return 
	 */
	public boolean isOccupied() {
	}

	/**
	 * 
	 * @param player 
	 * @return 
	 */
	public boolean canBuild(Player player) {
	}

	/**
	 * 
	 * @param building 
	 */
	public void placeBuilding(Buildings building) {
	}
}
